language: node_js
node_js:
  - 0.12
  - 0.11
  - 4.0
  - 4.1
  - 4.2
  - 5.0
  - iojs
os:
  - linux
#  - window
#  - osx
matrix:
  allow_failures:
    - os:
      - window
#       for travis nvm not found error
#      - osx
install:
  - npm install mocha -g
  - npm install
script:
  - npm test